general:
  cfApiEndpoint: 'https://api.cf.sap.hana.ondemand.com'
  cfOrg: 'myOrg'
  cfSpace: 'mySpace'
  cfCredentialsId: 'cfAuthentification'
  cfServiceInstance: 'atc_system'
stages:
  Prepare System:
    cfService: 'abap'
    cfServicePlan: 'standard'
    abapSystemAdminEmail: 'user@example.com'
    abapSystemDescription: 'ABAP Environment Q System'
    abapSystemIsDevelopmentAllowed: false
    abapSystemID: 'H02'
    abapSystemSizeOfPersistence: 4
    abapSystemSizeOfRuntime: 1
  Clone Repositories:
    repositories: 'repositories.yml'
    strategy: 'Clone'
  ATC:
    atcConfig: 'atcConfig.yml'
  AUnit:
    aUnitConfig: 'aUnitConfig.yml'
  Post:
    confirmDeletion: true
    cfDeleteServiceKeys: true
