general:
  abapCredentialsId: 'X08_piper'
  host: 'https://89df06df-af3b-4421-bcca-ea1f9284e51b.abap.stagingaws.hanavlab.ondemand.com'
stages:
  ATC:
    atcConfig: '/.pipeline/atcConfig.yml'
    atcSystemConfigFilePath: '/.pipeline/atcSystemConfig.json'
