general:
  abapCredentialsId: 'W11_PIPER'
  host: 'https://5a209ff1-8a85-4beb-a2cb-e47058e61367.abap.stagingaws.hanavlab.ondemand.com'
stages:
  ATC:
    atcConfig: '.pipeline/atcConfig.yml'
    atcSystemConfigFilePath: '.pipeline/atcSystemConfig.json'
