general:
  cfApiEndpoint: 'https://api.cf.sap.hana.ondemand.com'
  cfOrg: 'myOrg'
  cfSpace: 'mySpace'
  cfCredentialsId: 'cfAuthentification'
  cfServiceInstance: 'atc_system'
stages:
  Clone Repositories:
    repositories: 'repositories.yml'
    strategy: 'Pull'
  ATC:
    active: true
  AUnit:
    active: true
