general:
  cfApiEndpoint: 'https://api.cf.sap.hana.ondemand.com'
  cfOrg: 'myOrg'
  cfSpace: 'mySpace'
  cfCredentialsId: 'cfAuthentification'
  cfServiceInstance: 'atc_system'
  cfServiceKeyName: 'JENKINS_SAP_COM_0510'
stages:
  Clone Repositories:
    repositories: 'repositories.yml'
    strategy: 'Pull'
  ATC:
    atcConfig: 'atcConfig.yml'
  AUnit:
    aUnitConfig: 'aUnitConfig.yml'
